version: '3'

services:
  nginx: 
    image: nginx
    build: ./requirements/nginx
    ports:
      - 9000:80
    volumes:
      - ./requirements/wordpress:/etc/nginx/conf.d
    tty: true
    stdin_open: true
    depends_on:
      - wordpress
  wordpress: 
    image: wordpress
    build: ./requirements/wordpress
    volumes:
      - ./requirements/wordpress/content:/var/www/html
    environment: 
      - ./wordpress/.env
    depends_on:
      - db
  db:
    image: mariadb
    build: ./requirements/mariadb
    volumes:
      - ./requirements/mariadb:/var/lib/mysql
    environment:
      - ./.env
    
networks:
  default:
    external:
      name: nginx-proxy


