version: '3'

services:
  nginx: 
    image: nginx
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/logs:/var/log/nginx
      - ./requirements/wordpress/content:/var/www/html
    tty: true
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
    command:  /bin/sh -c "envsubst '$$DOMAIN_NAME' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    networks:
      - default
  wordpress: 
    image: wordpress
    build: requirements/wordpress
    volumes:
      - ./requirements/wordpress/content:/var/www/html
    expose:
      - 9000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
  db:
    image: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - ./requirements/mariadb/database:/var/lib/mysql
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    networks:
      - default
    
networks:
  default:
    driver: bridge

