version: '3'

services:
  nginx: 
    image: nginx:latest
    build: requirements/nginx
    ports:
      - 443:443
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - ./requirements/nginx/logs:/var/log/nginx
    tty: true
    stdin_open: true
    depends_on:
      - wordpress
    networks:
      - default
  wordpress: 
    image: wordpress:latest
    build: requirements/wordpress
    volumes:
      - ./requirements/wordpress/content:/var/www/html
    expose:
      - 9000
    environment: 
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=123456
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db
    networks:
      - default
  db:
    image: mariadb:latest
    build: requirements/mariadb
    volumes:
      - ./requirements/mariadb/database:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=wordpress
    networks:
      - default
    
networks:
  default:
    driver: bridge

