FROM mariadb:latest

EXPOSE 3306


VOLUME [ "/var/lib/mysql" ]

# FROM debian:11

# RUN apt-get update && apt-get upgrade -y

# RUN apt-get install -y mariadb-server

# COPY tool/docker-entrypoint.sh /bin/docker-entrypoint.sh

# EXPOSE 3306

# VOLUME [ "/var/lib/mysql" ]

# CMD ["/bin/sh", "/bin/docker-entrypoint.sh"]